added a guide to optimize queries
duneanalytics/docs pull request #237
Opened 2023-01-10 08:00 UTC by SusmeetJain

2023-01-10 18:52 UTC, davidkell requested changes

2023-01-10 18:52 UTC, davidkell commented on docs/api/quick-start/optimization.md
> +Until your code looks ready and has been tested to fetch the data you need, use the `LIMIT` keyword at the end of any SQL query you are fetching data from.
Here you can provide the context - as the Dune API bills by datapoints

2023-01-10 18:52 UTC, davidkell commented on docs/api/quick-start/optimization.md
> +If you are using queries prepared by accounts other than yours, you can fork and then edit those queries to add this little change.
remove "little"

2023-01-10 18:52 UTC, davidkell commented on docs/api/quick-start/optimization.md
> +    If there is data that you frequently need to call with the API. You can store it locally. And use your local database for that data. You can also keep updating this data dynamically using the tip
Some of these full stops don't make sense

e.g. "If there is data that you frequently need to call with the API, we recommend that you can store it locally e.g. in a database."

2023-01-27 03:24 UTC, andrewhong5297 commented
this may need to be updated to the new routing paths before merging

2023-02-09 20:13 UTC, closed without merging